# Generated by Django 4.2.1 on 2023-05-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('CI', models.CharField(verbose_name='CI')),
                ('destino', models.CharField(max_length=50, verbose_name='Destino')),
                ('origen', models.CharField(max_length=50, verbose_name='Origen')),
                ('costo_Pasaje', models.IntegerField(verbose_name='costo pasaje')),
                ('fecha', models.DateField(verbose_name='Fecha')),
            ],
        ),
    ]
