# Generated by Django 4.2.1 on 2023-05-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facultad4app', '0002_dieta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('fac', models.CharField(verbose_name='Facultad')),
                ('dir', models.CharField(verbose_name='Direccion')),
                ('CI', models.CharField(verbose_name='CI')),
                ('prov', models.CharField(verbose_name='Provincia')),
                ('mun', models.CharField(verbose_name='Municipio')),
                ('sol', models.CharField(verbose_name='Solapin')),
                ('fechaC', models.DateField(verbose_name='Fecha Inicio de creacion')),
                ('fechaA', models.DateField(verbose_name='Fecha Fin de aprobacion')),
            ],
        ),
    ]
