# Generated by Django 4.2.1 on 2023-06-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facultad4app', '0003_expediente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('fechaI', models.DateField(verbose_name='Fecha Inicio del Prestamo')),
                ('fechaF', models.DateField(verbose_name='Fecha Fin del Prestamo')),
                ('cant', models.IntegerField(verbose_name='cant')),
            ],
        ),
    ]
